# action.yml
name: 'Archinaut action'
description: 'Executes Archinaut metric analysis given a configuration file provided and a series of metrics reports available at runtime.'
inputs:
  configuration file:
    description: 'Path to the configuration file that holds the Archinaut settings in a YAML format.'
    required: true
    default: 'archinaut.yml'
  init date:
    description: 'Starting date to analyze git log from, format is: yyyy-mm-dd.'
    required: false
  min cochanges:
    description: 'Minimum number of cochanges to report in coupling analysis.'
    required: false
    default: '0'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
    icon: "code"
    color: "black"
